---
- name: gify-panda app
  copy: src=gify-panda-app dest=/srv/devopsbp owner=root group=root mode=0755

- name: npm install
  npm: path=/srv/devopsbp/gify-panda-app

- name: Install "forever" node.js package globally.
  npm:
    name: forever
    global: yes
