---
  - name: gify-panda app
    copy: src=gify-panda-app dest=/srv/devopsbp owner=root group=root mode=0755

  - name: npm install
    npm: path=/srv/devopsbp/gify-panda-app

  - name: Install "forever" node.js package globally.
    npm:
      name: forever
      global: yes

  - name: Add forever nodejs init.d script
    action: template src=templates/nodejs_daemon.template dest=/etc/init.d/{{service_name}}  owner=root group=root mode=0755

  - name: Ensure gify-panda service is started
    action: service name=gify-panda state=started
