---
- name: Common tasks FTW
  hosts: all
  become: yes
  pre_tasks:
    - name: Set hostname
      hostname: name={{inventory_hostname}}

- name: Base counter-panda service
  hosts: base
  become: yes
  roles:
    - { role: nodejs, tags: nodejs }
    - { role: counter-panda, tags: counter-panda }
